# -*- coding: utf-8 -*-
"""sigma_data_generator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DyqUfXFc8r8CBN1spdPlmQ43SbcekplK
"""

import pandas as pd
import numpy as np

# --- MODULE 1: THE ROSTER SETTINGS ---
# Defining the team sizes we discussed
HINDI_SPECS = {'lang': 'Hindi', 'trans': 21, 'rev': 7}
ENGLISH_SPECS = {'lang': 'English', 'trans': 22, 'rev': 10}

def generate_roster():
    workers = []
    # Hindi Roster
    for i in range(1, 29):
        team = 'Transcription' if i <= 21 else 'Review'
        workers.append({'id': f'H_{i:02d}', 'lang': 'Hindi', 'team': team})
    # English Roster
    for i in range(1, 33):
        team = 'Transcription' if i <= 22 else 'Review'
        workers.append({'id': f'E_{i:02d}', 'lang': 'English', 'team': team})
    return workers

# --- MODULE 2: THE PERFORMANCE LOGIC (The "Story" Engine) ---
def get_daily_performance(worker, date):
    q = (date.month - 1) // 3 + 1  # Logic to determine Quarter (1, 2, 3, or 4)
    team = worker['team']
    lang = worker['lang']

    # Default Targets
    target = 270 if team == 'Transcription' else 500

    # --- Q1: THE CRISIS LOGIC ---
    if q == 1:
        if lang == 'Hindi' and team == 'Review':
            # Hindi Reviewers are drowning
            speed = np.random.randint(440, 465)
            error_chance = 0.092 # 9.2% probability
        elif lang == 'English' and team == 'Transcription':
            # English New Hires are slow/messy
            speed = np.random.randint(215, 235)
            error_chance = 0.148
        else:
            # Other teams are doing well
            speed = np.random.randint(target + 5, target + 15)
            error_chance = 0.045 if team == 'Transcription' else 0.026

    # --- Q2: THE INTERVENTION LOGIC ---
    elif q == 2:
        # Simulate the "Shuffle" for Hindi Review
        if lang == 'Hindi' and team == 'Review':
            speed = np.random.randint(490, 505)
            error_chance = 0.048
        # English New Hires improving via Mentors
        elif lang == 'English' and team == 'Transcription':
            speed = np.random.randint(240, 255)
            error_chance = 0.098
        else:
            speed = np.random.randint(target - 5, target + 10)
            error_chance = 0.065 # Transcription took a slight hit for the move

    # --- Q3 & Q4: STABILIZATION & GOLD STANDARD ---
    else:
        # Continuous improvement towards year end
        boost = 5 if q == 3 else 15
        speed = np.random.randint(target + boost - 5, target + boost + 5)
        error_chance = 0.035 if team == 'Review' else 0.060

    return speed, error_chance, target

# --- MODULE 3: THE AUDIT ENGINE (The Random Sampling) ---
dates = pd.date_range(start='2026-01-01', end='2026-12-31', freq='D')
roster = generate_roster()
master_data = []

for date in dates:
    for worker in roster:
        speed, error_chance, target = get_daily_performance(worker, date)

        # YOUR RANDOM SAMPLING LOGIC:
        # Sample size between 15 and 30 units
        sample_n = np.random.randint(15, 31)

        # Errors found is based on the "error_chance" for that Quarter/Team
        errors_e = np.random.binomial(sample_n, error_chance)

        # Calculate Rate (E / N)
        error_rate = (errors_e / sample_n) * 100

        # Assign Error Hierarchy
        if errors_e == 0:
            hierarchy = 'None'
            err_type = 'None'
        else:
            # If errors exist, pick a random type
            hierarchy = np.random.choice(['Critical', 'Major', 'Minor'], p=[0.1, 0.3, 0.6])
            err_type = np.random.choice(['Orthographic', 'Formatting', 'Guideline', 'Audio'])

        master_data.append([
            date, f"Q{ (date.month - 1) // 3 + 1 }", worker['id'],
            worker['lang'], worker['team'], target, speed,
            sample_n, errors_e, round(error_rate, 2), hierarchy, err_type
        ])

# --- MODULE 4: EXPORT ---
df = pd.DataFrame(master_data, columns=[
    'Date', 'Quarter', 'Worker_ID', 'Language', 'Team',
    'Target', 'Actual_Output', 'Sample_Size', 'Errors_Found',
    'Error_Pct', 'Hierarchy', 'Error_Type'
])

df.to_csv('Master_Ops_Data_2026.csv', index=False)
print("SUCCESS: 12-Month Master Dataset Created with 21,900 rows.")